# Generated by Django 4.2.7 on 2023-12-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailconfirmationtoken',
            options={'verbose_name': 'Email Confirmation Token', 'verbose_name_plural': 'Email Confirmation Tokens'},
        ),
    ]
