# Generated by Django 4.2.7 on 2023-12-28 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_emailconfirmationtoken_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
