# Generated by Django 4.2.7 on 2023-12-28 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_verified_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmationtoken',
            name='token',
        ),
    ]
