# Generated by Django 5.0.1 on 2024-02-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
