# Generated by Django 4.2.7 on 2023-11-18 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'User Profiles', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='usertokens',
            options={'verbose_name': 'User Tokens', 'verbose_name_plural': 'User Tokens'},
        ),
        migrations.RemoveField(
            model_name='usertokens',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user email'),
        ),
    ]
