# Generated by Django 4.2.7 on 2023-11-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_usertokens_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertokens',
            old_name='access_token',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='usertokens',
            name='refresh_token',
        ),
        migrations.AlterField(
            model_name='usertokens',
            name='user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='user email'),
        ),
    ]
