# Generated by Django 4.2.7 on 2023-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usertokens_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertokens',
            old_name='user',
            new_name='email',
        ),
    ]
