# Generated by Django 4.2.7 on 2023-11-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_user_usertokens_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='token',
            field=models.CharField(max_length=5000),
        ),
    ]
